// Generated by tmpl
// https://github.com/benbjohnson/tmpl
//
// DO NOT EDIT!
// Source: engine.gen.go.tmpl

package tsm1

import (
	"context"
	"github.com/influxdata/influxdb/query"
	"github.com/influxdata/influxql"
	"math"
)

// buildFloatCursor creates a cursor for a float field.
func (e *Engine) buildFloatCursor(ctx context.Context, measurement, seriesKey, field string, opt query.IteratorOptions) floatCursor {
	key := SeriesFieldKeyBytes(seriesKey, field)
	cacheValues := e.Cache.Values(key)
	keyCursor := e.KeyCursor(ctx, key, opt.SeekTime(), opt.Ascending)
	return newFloatCursor(opt.SeekTime(), opt.Ascending, cacheValues, keyCursor)
}

func (e *Engine) buildFloatCursorForGroup2(ctx context.Context, measurement, groupKey string, sequenceKeys []string, field string, opt query.IteratorOptions) []floatCursor {
	// (1)查Cache
	cacheValues := e.Cache.ValuesForGroup2([]byte(groupKey), sequenceKeys) // 获取了multivalue， 封装成原来的样子
	fields := e.fieldset.Fields([]byte(measurement))
	index := fields.Field(field).ID       // 获取到field的ID，就是multivalue的位置
	fieldType := fields.Field(field).Type //根据数据类型来封装

	// 封装cache value
	newCacheValues := make(map[string]Values)
	for _, sequenceKey := range sequenceKeys {
		switch fieldType {
		case influxql.Float:
			for _, multiValue := range cacheValues[sequenceKey] {
				// 过滤默认值
				if multiValue.Val[index].Value().(float64) == -math.MaxFloat64 {
					continue
				}
				newCacheValues[sequenceKey] = append(newCacheValues[sequenceKey], FloatValue{
					unixnano: multiValue.Ts,
					value:    multiValue.Val[index].Value().(float64),
				})
			}
		default:
			panic("unreachable")
		}
	}

	// （2）查TSM文件,把数据全部查出来再根据Field过滤,这里已经查出了GroupEntry和SequenceEntry
	keyCursor := e.KeyCursorForGroup3(ctx, []byte(groupKey), sequenceKeys, opt.SeekTime(), opt.Ascending)
	var exprString string
	if opt.Expr != nil {
		exprString = opt.Expr.String()
	} else {
		exprString = ""
	}
	return newFloatCursorForGroup2(opt.StartTime, opt.EndTime, opt.Ascending, exprString, opt.Interval.Duration, newCacheValues, keyCursor, int(index))
}

func (e *Engine) buildFloatCursorForGroup(ctx context.Context, measurement, groupKey, sequenceKey, field string, opt query.IteratorOptions) floatCursor {
	// (1)查Cache
	cacheValues := e.Cache.ValuesForGroup([]byte(groupKey), []byte(sequenceKey)) // 获取了multivalue， 封装成原来的样子
	fields := e.fieldset.Fields([]byte(measurement))
	index := fields.Field(field).ID       // 获取到field的ID，就是multivalue的位置
	fieldType := fields.Field(field).Type //根据数据类型来封装

	// 封装cache value
	newCacheValues := make(Values, 0)
	switch fieldType {
	case influxql.Float:
		for _, multiValue := range cacheValues {
			// 过滤默认值
			if multiValue.Val[index].Value().(float64) == -math.MaxFloat64 {
				continue
			}
			newCacheValues = append(newCacheValues, FloatValue{
				unixnano: multiValue.Ts,
				value:    multiValue.Val[index].Value().(float64),
			})
		}
	default:
		panic("unreachable")
	}

	// （2）查TSM文件,把数据全部查出来再根据Field过滤,这里已经查出了GroupEntry和SequenceEntry
	keyCursor := e.KeyCursorForGroup(ctx, []byte(groupKey), []byte(sequenceKey), opt.SeekTime(), opt.Ascending)
	var exprString string
	if opt.Expr != nil {
		exprString = opt.Expr.String()
	} else {
		exprString = ""
	}
	return newFloatCursorForGroup(opt.StartTime, opt.EndTime, opt.Ascending, exprString, opt.Interval.Duration, newCacheValues, keyCursor, int(index))
}

// buildIntegerCursor creates a cursor for a integer field.
func (e *Engine) buildIntegerCursor(ctx context.Context, measurement, seriesKey, field string, opt query.IteratorOptions) integerCursor {

	key := SeriesFieldKeyBytes(seriesKey, field)
	cacheValues := e.Cache.Values(key)

	//根据seriesKey和field生成tsmKey

	keyCursor := e.KeyCursor(ctx, key, opt.SeekTime(), opt.Ascending)
	return newIntegerCursor(opt.SeekTime(), opt.Ascending, cacheValues, keyCursor)
}

func (e *Engine) buildIntegerCursorForGroup2(ctx context.Context, measurement, groupKey string, sequenceKeys []string, field string, opt query.IteratorOptions) []integerCursor {
	// (1)查Cache
	cacheValues := e.Cache.ValuesForGroup2([]byte(groupKey), sequenceKeys) // 获取了multivalue， 封装成原来的样子
	fields := e.fieldset.Fields([]byte(measurement))
	index := fields.Field(field).ID       // 获取到field的ID，就是multivalue的位置
	fieldType := fields.Field(field).Type //根据数据类型来封装

	// 封装cache value
	newCacheValues := make(map[string]Values)
	for _, sequenceKey := range sequenceKeys {
		switch fieldType {
		case influxql.Integer:
			for _, multiValue := range cacheValues[sequenceKey] {
				// 过滤默认值
				if multiValue.Val[index].Value().(int64) == -math.MaxInt64 {
					continue
				}
				newCacheValues[sequenceKey] = append(newCacheValues[sequenceKey], IntegerValue{
					unixnano: multiValue.Ts,
					value:    multiValue.Val[index].Value().(int64),
				})
			}
		default:
			panic("unreachable")
		}
	}

	// （2）查TSM文件,把数据全部查出来再根据Field过滤,这里已经查出了GroupEntry和SequenceEntry
	keyCursor := e.KeyCursorForGroup3(ctx, []byte(groupKey), sequenceKeys, opt.SeekTime(), opt.Ascending)
	var exprString string
	if opt.Expr != nil {
		exprString = opt.Expr.String()
	} else {
		exprString = ""
	}

	return newIntegerCursorForGroup2(opt.StartTime, opt.EndTime, opt.Ascending, exprString, opt.Interval.Duration, newCacheValues, keyCursor, int(index))

}

// TODO: 因为在这个函数里查出了所有数据，然后对上层进行封装，所以在这里区分 查出一个组的数据丢到存储引擎里，然后如果有数据直接从存储引擎里拿
func (e *Engine) buildIntegerCursorForGroup(ctx context.Context, measurement, groupKey, sequenceKey, field string, opt query.IteratorOptions) integerCursor {
	// (1)查Cache
	cacheValues := e.Cache.ValuesForGroup([]byte(groupKey), []byte(sequenceKey)) // 获取了multivalue， 封装成原来的样子
	fields := e.fieldset.Fields([]byte(measurement))
	index := fields.Field(field).ID       // 获取到field的ID，就是multivalue的位置
	fieldType := fields.Field(field).Type //根据数据类型来封装

	// 封装cache value
	newCacheValues := make(Values, 0)
	switch fieldType {
	case influxql.Integer:
		for _, multiValue := range cacheValues {
			// 过滤默认值
			if multiValue.Val[index].Value().(int64) == -math.MaxInt64 {
				continue
			}
			newCacheValues = append(newCacheValues, IntegerValue{
				unixnano: multiValue.Ts,
				value:    multiValue.Val[index].Value().(int64),
			})
		}
	default:
		panic("unreachable")
	}

	// （2）查TSM文件,把数据全部查出来再根据Field过滤,这里已经查出了GroupEntry和SequenceEntry
	keyCursor := e.KeyCursorForGroup(ctx, []byte(groupKey), []byte(sequenceKey), opt.SeekTime(), opt.Ascending)
	var exprString string
	if opt.Expr != nil {
		exprString = opt.Expr.String()
	} else {
		exprString = ""
	}

	return newIntegerCursorForGroup(opt.StartTime, opt.EndTime, opt.Ascending, exprString, opt.Interval.Duration, newCacheValues, keyCursor, int(index))
}

// buildUnsignedCursor creates a cursor for a unsigned field.
func (e *Engine) buildUnsignedCursor(ctx context.Context, measurement, seriesKey, field string, opt query.IteratorOptions) unsignedCursor {
	key := SeriesFieldKeyBytes(seriesKey, field)
	cacheValues := e.Cache.Values(key)
	keyCursor := e.KeyCursor(ctx, key, opt.SeekTime(), opt.Ascending)
	return newUnsignedCursor(opt.SeekTime(), opt.Ascending, cacheValues, keyCursor)
}

// buildStringCursor creates a cursor for a string field.
func (e *Engine) buildStringCursor(ctx context.Context, measurement, seriesKey, field string, opt query.IteratorOptions) stringCursor {
	key := SeriesFieldKeyBytes(seriesKey, field)
	cacheValues := e.Cache.Values(key)
	keyCursor := e.KeyCursor(ctx, key, opt.SeekTime(), opt.Ascending)
	return newStringCursor(opt.SeekTime(), opt.Ascending, cacheValues, keyCursor)
}

// buildBooleanCursor creates a cursor for a boolean field.
func (e *Engine) buildBooleanCursor(ctx context.Context, measurement, seriesKey, field string, opt query.IteratorOptions) booleanCursor {
	key := SeriesFieldKeyBytes(seriesKey, field)
	cacheValues := e.Cache.Values(key)
	keyCursor := e.KeyCursor(ctx, key, opt.SeekTime(), opt.Ascending)
	return newBooleanCursor(opt.SeekTime(), opt.Ascending, cacheValues, keyCursor)
}
