// Code generated by file_store.gen.go.tmpl. DO NOT EDIT.

package tsm1

import (
	"math"
	"strings"
	"time"
)


type downSample struct {
	min, max 	int64
	avg      	float64
	valueLen 	int
}

func (c *KeyCursor2) ReadFloatBlock(buf *[]FloatValue) ([]FloatValue, error) {
LOOP:
	// No matching blocks to decode
	if len(c.current) == 0 {
		return nil, nil
	}

	// First block is the oldest block containing the points we're searching for.
	first := c.current[0]
	*buf = (*buf)[:0]
	var values FloatValues
	values, err := first.r.ReadFloatBlockAt(&first.entry, buf)
	if err != nil {
		return nil, err
	}
	if c.col != nil {
		c.col.GetCounter(floatBlocksDecodedCounter).Add(1)
		c.col.GetCounter(floatBlocksSizeCounter).Add(int64(first.entry.Size))
	}

	// Remove values we already read
	values = values.Exclude(first.readMin, first.readMax)

	// Remove any tombstones
	tombstones := first.r.TombstoneRange(c.key)
	values = excludeTombstonesFloatValues(tombstones, values)
	// If there are no values in this first block (all tombstoned or previously read) and
	// we have more potential blocks too search.  Try again.
	if values.Len() == 0 && len(c.current) > 0 {
		c.current = c.current[1:]
		goto LOOP
	}

	// Only one block with this key and time range so return it
	if len(c.current) == 1 {
		if values.Len() > 0 {
			first.markRead(values.MinTime(), values.MaxTime())
		}
		return values, nil
	}

	// Use the current block time range as our overlapping window
	minT, maxT := first.readMin, first.readMax
	if values.Len() > 0 {
		minT, maxT = values.MinTime(), values.MaxTime()
	}
	if c.ascending {
		// Blocks are ordered by generation, we may have values in the past in later blocks, if so,
		// expand the window to include the min time range to ensure values are returned in ascending
		// order
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.MinTime < minT && !cur.read() {
				minT = cur.entry.MinTime
			}
		}

		// Find first block that overlaps our window
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.OverlapsTimeRange(minT, maxT) && !cur.read() {
				// Shrink our window so it's the intersection of the first overlapping block and the
				// first block.  We do this to minimize the region that overlaps and needs to
				// be merged.
				if cur.entry.MaxTime > maxT {
					maxT = cur.entry.MaxTime
				}
				values = values.Include(minT, maxT)
				break
			}
		}

		// Search the remaining blocks that overlap our window and append their values so we can
		// merge them.
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			// Skip this block if it doesn't contain points we looking for or they have already been read
			if !cur.entry.OverlapsTimeRange(minT, maxT) || cur.read() {
				cur.markRead(minT, maxT)
				continue
			}

			var a []FloatValue
			var v FloatValues
			v, err := cur.r.ReadFloatBlockAt(&cur.entry, &a)
			if err != nil {
				return nil, err
			}
			if c.col != nil {
				c.col.GetCounter(floatBlocksDecodedCounter).Add(1)
				c.col.GetCounter(floatBlocksSizeCounter).Add(int64(cur.entry.Size))
			}

			tombstones := cur.r.TombstoneRange(c.key)
			// Remove any tombstoned values
			v = excludeTombstonesFloatValues(tombstones, v)

			// Remove values we already read
			v = v.Exclude(cur.readMin, cur.readMax)

			if v.Len() > 0 {
				// Only use values in the overlapping window
				v = v.Include(minT, maxT)
				// Merge the remaining values with the existing
				values = values.Merge(v)
			}
			cur.markRead(minT, maxT)
		}

	} else {
		// Blocks are ordered by generation, we may have values in the past in later blocks, if so,
		// expand the window to include the max time range to ensure values are returned in descending
		// order
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.MaxTime > maxT && !cur.read() {
				maxT = cur.entry.MaxTime
			}
		}

		// Find first block that overlaps our window
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.OverlapsTimeRange(minT, maxT) && !cur.read() {
				// Shrink our window so it's the intersection of the first overlapping block and the
				// first block.  We do this to minimize the region that overlaps and needs to
				// be merged.
				if cur.entry.MinTime < minT {
					minT = cur.entry.MinTime
				}
				values = values.Include(minT, maxT)
				break
			}
		}

		// Search the remaining blocks that overlap our window and append their values so we can
		// merge them.
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			// Skip this block if it doesn't contain points we looking for or they have already been read
			if !cur.entry.OverlapsTimeRange(minT, maxT) || cur.read() {
				cur.markRead(minT, maxT)
				continue
			}

			var a []FloatValue
			var v FloatValues
			v, err := cur.r.ReadFloatBlockAt(&cur.entry, &a)
			if err != nil {
				return nil, err
			}
			if c.col != nil {
				c.col.GetCounter(floatBlocksDecodedCounter).Add(1)
				c.col.GetCounter(floatBlocksSizeCounter).Add(int64(cur.entry.Size))
			}
			tombstones := cur.r.TombstoneRange(c.key)
			// Remove any tombstoned values
			v = excludeTombstonesFloatValues(tombstones, v)

			// Remove values we already read
			v = v.Exclude(cur.readMin, cur.readMax)

			// If the block we decoded should have all of it's values included, mark it as read so we
			// don't use it again.
			if v.Len() > 0 {
				v = v.Include(minT, maxT)
				// Merge the remaining values with the existing
				values = v.Merge(values)
			}
			cur.markRead(minT, maxT)
		}
	}

	first.markRead(minT, maxT)

	return values, err
}


// ReadFloatBlock reads the next block as a set of float values.
func (c *KeyCursor) ReadFloatBlock(buf *[]FloatValue) ([]FloatValue, error) {
LOOP:
	// No matching blocks to decode
	if len(c.current) == 0 {
		return nil, nil
	}

	// First block is the oldest block containing the points we're searching for.
	first := c.current[0]
	*buf = (*buf)[:0]
	var values FloatValues
	values, err := first.r.ReadFloatBlockAt(&first.entry, buf)
	if err != nil {
		return nil, err
	}
	if c.col != nil {
		c.col.GetCounter(floatBlocksDecodedCounter).Add(1)
		c.col.GetCounter(floatBlocksSizeCounter).Add(int64(first.entry.Size))
	}

	// Remove values we already read
	values = values.Exclude(first.readMin, first.readMax)

	// Remove any tombstones
	tombstones := first.r.TombstoneRange(c.key)
	values = excludeTombstonesFloatValues(tombstones, values)
	// If there are no values in this first block (all tombstoned or previously read) and
	// we have more potential blocks too search.  Try again.
	if values.Len() == 0 && len(c.current) > 0 {
		c.current = c.current[1:]
		goto LOOP
	}

	// Only one block with this key and time range so return it
	if len(c.current) == 1 {
		if values.Len() > 0 {
			first.markRead(values.MinTime(), values.MaxTime())
		}
		return values, nil
	}

	// Use the current block time range as our overlapping window
	minT, maxT := first.readMin, first.readMax
	if values.Len() > 0 {
		minT, maxT = values.MinTime(), values.MaxTime()
	}
	if c.ascending {
		// Blocks are ordered by generation, we may have values in the past in later blocks, if so,
		// expand the window to include the min time range to ensure values are returned in ascending
		// order
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.MinTime < minT && !cur.read() {
				minT = cur.entry.MinTime
			}
		}

		// Find first block that overlaps our window
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.OverlapsTimeRange(minT, maxT) && !cur.read() {
				// Shrink our window so it's the intersection of the first overlapping block and the
				// first block.  We do this to minimize the region that overlaps and needs to
				// be merged.
				if cur.entry.MaxTime > maxT {
					maxT = cur.entry.MaxTime
				}
				values = values.Include(minT, maxT)
				break
			}
		}

		// Search the remaining blocks that overlap our window and append their values so we can
		// merge them.
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			// Skip this block if it doesn't contain points we looking for or they have already been read
			if !cur.entry.OverlapsTimeRange(minT, maxT) || cur.read() {
				cur.markRead(minT, maxT)
				continue
			}

			var a []FloatValue
			var v FloatValues
			v, err := cur.r.ReadFloatBlockAt(&cur.entry, &a)
			if err != nil {
				return nil, err
			}
			if c.col != nil {
				c.col.GetCounter(floatBlocksDecodedCounter).Add(1)
				c.col.GetCounter(floatBlocksSizeCounter).Add(int64(cur.entry.Size))
			}

			tombstones := cur.r.TombstoneRange(c.key)
			// Remove any tombstoned values
			v = excludeTombstonesFloatValues(tombstones, v)

			// Remove values we already read
			v = v.Exclude(cur.readMin, cur.readMax)

			if v.Len() > 0 {
				// Only use values in the overlapping window
				v = v.Include(minT, maxT)
				// Merge the remaining values with the existing
				values = values.Merge(v)
			}
			cur.markRead(minT, maxT)
		}

	} else {
		// Blocks are ordered by generation, we may have values in the past in later blocks, if so,
		// expand the window to include the max time range to ensure values are returned in descending
		// order
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.MaxTime > maxT && !cur.read() {
				maxT = cur.entry.MaxTime
			}
		}

		// Find first block that overlaps our window
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.OverlapsTimeRange(minT, maxT) && !cur.read() {
				// Shrink our window so it's the intersection of the first overlapping block and the
				// first block.  We do this to minimize the region that overlaps and needs to
				// be merged.
				if cur.entry.MinTime < minT {
					minT = cur.entry.MinTime
				}
				values = values.Include(minT, maxT)
				break
			}
		}

		// Search the remaining blocks that overlap our window and append their values so we can
		// merge them.
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			// Skip this block if it doesn't contain points we looking for or they have already been read
			if !cur.entry.OverlapsTimeRange(minT, maxT) || cur.read() {
				cur.markRead(minT, maxT)
				continue
			}

			var a []FloatValue
			var v FloatValues
			v, err := cur.r.ReadFloatBlockAt(&cur.entry, &a)
			if err != nil {
				return nil, err
			}
			if c.col != nil {
				c.col.GetCounter(floatBlocksDecodedCounter).Add(1)
				c.col.GetCounter(floatBlocksSizeCounter).Add(int64(cur.entry.Size))
			}
			tombstones := cur.r.TombstoneRange(c.key)
			// Remove any tombstoned values
			v = excludeTombstonesFloatValues(tombstones, v)

			// Remove values we already read
			v = v.Exclude(cur.readMin, cur.readMax)

			// If the block we decoded should have all of it's values included, mark it as read so we
			// don't use it again.
			if v.Len() > 0 {
				v = v.Include(minT, maxT)
				// Merge the remaining values with the existing
				values = v.Merge(values)
			}
			cur.markRead(minT, maxT)
		}
	}

	first.markRead(minT, maxT)

	return values, err
}

func excludeTombstonesFloatValues(t []TimeRange, values FloatValues) FloatValues {
	for i := range t {
		values = values.Exclude(t[i].Min, t[i].Max)
	}
	return values
}

// ReadIntegerBlock reads the next block as a set of integer values.
func (c *KeyCursor) ReadIntegerBlock(buf *[]IntegerValue) ([]IntegerValue, error) {
LOOP:
	// No matching blocks to decode
	if len(c.current) == 0 {
		return nil, nil
	}

	// First block is the oldest block containing the points we're searching for.
	first := c.current[0]
	*buf = (*buf)[:0]
	var values IntegerValues
	values, err := first.r.ReadIntegerBlockAt(&first.entry, buf)
	if err != nil {
		return nil, err
	}
	if c.col != nil {
		c.col.GetCounter(integerBlocksDecodedCounter).Add(1)
		c.col.GetCounter(integerBlocksSizeCounter).Add(int64(first.entry.Size))
	}

	// Remove values we already read
	values = values.Exclude(first.readMin, first.readMax)

	// Remove any tombstones
	tombstones := first.r.TombstoneRange(c.key)
	values = excludeTombstonesIntegerValues(tombstones, values)
	// If there are no values in this first block (all tombstoned or previously read) and
	// we have more potential blocks too search.  Try again.
	if values.Len() == 0 && len(c.current) > 0 {
		c.current = c.current[1:]
		goto LOOP
	}

	// Only one block with this key and time range so return it
	if len(c.current) == 1 {
		if values.Len() > 0 {
			first.markRead(values.MinTime(), values.MaxTime())
		}
		return values, nil
	}

	// Use the current block time range as our overlapping window
	minT, maxT := first.readMin, first.readMax
	if values.Len() > 0 {
		minT, maxT = values.MinTime(), values.MaxTime()
	}
	if c.ascending {
		// Blocks are ordered by generation, we may have values in the past in later blocks, if so,
		// expand the window to include the min time range to ensure values are returned in ascending
		// order
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.MinTime < minT && !cur.read() {
				minT = cur.entry.MinTime
			}
		}

		// Find first block that overlaps our window
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.OverlapsTimeRange(minT, maxT) && !cur.read() {
				// Shrink our window so it's the intersection of the first overlapping block and the
				// first block.  We do this to minimize the region that overlaps and needs to
				// be merged.
				if cur.entry.MaxTime > maxT {
					maxT = cur.entry.MaxTime
				}
				values = values.Include(minT, maxT)
				break
			}
		}

		// Search the remaining blocks that overlap our window and append their values so we can
		// merge them.
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			// Skip this block if it doesn't contain points we looking for or they have already been read
			if !cur.entry.OverlapsTimeRange(minT, maxT) || cur.read() {
				cur.markRead(minT, maxT)
				continue
			}

			var a []IntegerValue
			var v IntegerValues
			v, err := cur.r.ReadIntegerBlockAt(&cur.entry, &a)
			if err != nil {
				return nil, err
			}
			if c.col != nil {
				c.col.GetCounter(integerBlocksDecodedCounter).Add(1)
				c.col.GetCounter(integerBlocksSizeCounter).Add(int64(cur.entry.Size))
			}

			tombstones := cur.r.TombstoneRange(c.key)
			// Remove any tombstoned values
			v = excludeTombstonesIntegerValues(tombstones, v)

			// Remove values we already read
			v = v.Exclude(cur.readMin, cur.readMax)

			if v.Len() > 0 {
				// Only use values in the overlapping window
				v = v.Include(minT, maxT)
				// Merge the remaining values with the existing
				values = values.Merge(v)
			}
			cur.markRead(minT, maxT)
		}

	} else {
		// Blocks are ordered by generation, we may have values in the past in later blocks, if so,
		// expand the window to include the max time range to ensure values are returned in descending
		// order
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.MaxTime > maxT && !cur.read() {
				maxT = cur.entry.MaxTime
			}
		}

		// Find first block that overlaps our window
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.OverlapsTimeRange(minT, maxT) && !cur.read() {
				// Shrink our window so it's the intersection of the first overlapping block and the
				// first block.  We do this to minimize the region that overlaps and needs to
				// be merged.
				if cur.entry.MinTime < minT {
					minT = cur.entry.MinTime
				}
				values = values.Include(minT, maxT)
				break
			}
		}

		// Search the remaining blocks that overlap our window and append their values so we can
		// merge them.
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			// Skip this block if it doesn't contain points we looking for or they have already been read
			if !cur.entry.OverlapsTimeRange(minT, maxT) || cur.read() {
				cur.markRead(minT, maxT)
				continue
			}

			var a []IntegerValue
			var v IntegerValues
			v, err := cur.r.ReadIntegerBlockAt(&cur.entry, &a)
			if err != nil {
				return nil, err
			}
			if c.col != nil {
				c.col.GetCounter(integerBlocksDecodedCounter).Add(1)
				c.col.GetCounter(integerBlocksSizeCounter).Add(int64(cur.entry.Size))
			}
			tombstones := cur.r.TombstoneRange(c.key)
			// Remove any tombstoned values
			v = excludeTombstonesIntegerValues(tombstones, v)

			// Remove values we already read
			v = v.Exclude(cur.readMin, cur.readMax)

			// If the block we decoded should have all of it's values included, mark it as read so we
			// don't use it again.
			if v.Len() > 0 {
				v = v.Include(minT, maxT)
				// Merge the remaining values with the existing
				values = v.Merge(values)
			}
			cur.markRead(minT, maxT)
		}
	}

	first.markRead(minT, maxT)

	return values, err
}

func (c *KeyCursor2) ReadIntegerBlock(buf *[]IntegerValue) ([]IntegerValue, error) {
LOOP:
	// No matching blocks to decode
	if len(c.current) == 0 {
		return nil, nil
	}

	// First block is the oldest block containing the points we're searching for.
	first := c.current[0]
	*buf = (*buf)[:0]
	var values IntegerValues
	values, err := first.r.ReadIntegerBlockAt(&first.entry, buf)
	if err != nil {
		return nil, err
	}
	if c.col != nil {
		c.col.GetCounter(integerBlocksDecodedCounter).Add(1)
		c.col.GetCounter(integerBlocksSizeCounter).Add(int64(first.entry.Size))
	}

	// Remove values we already read
	values = values.Exclude(first.readMin, first.readMax)

	// Remove any tombstones
	tombstones := first.r.TombstoneRange(c.key)
	values = excludeTombstonesIntegerValues(tombstones, values)
	// If there are no values in this first block (all tombstoned or previously read) and
	// we have more potential blocks too search.  Try again.
	if values.Len() == 0 && len(c.current) > 0 {
		c.current = c.current[1:]
		goto LOOP
	}

	// Only one block with this key and time range so return it
	if len(c.current) == 1 {
		if values.Len() > 0 {
			first.markRead(values.MinTime(), values.MaxTime())
		}
		return values, nil
	}

	// Use the current block time range as our overlapping window
	minT, maxT := first.readMin, first.readMax
	if values.Len() > 0 {
		minT, maxT = values.MinTime(), values.MaxTime()
	}
	if c.ascending {
		// Blocks are ordered by generation, we may have values in the past in later blocks, if so,
		// expand the window to include the min time range to ensure values are returned in ascending
		// order
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.MinTime < minT && !cur.read() {
				minT = cur.entry.MinTime
			}
		}

		// Find first block that overlaps our window
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.OverlapsTimeRange(minT, maxT) && !cur.read() {
				// Shrink our window so it's the intersection of the first overlapping block and the
				// first block.  We do this to minimize the region that overlaps and needs to
				// be merged.
				if cur.entry.MaxTime > maxT {
					maxT = cur.entry.MaxTime
				}
				values = values.Include(minT, maxT)
				break
			}
		}

		// Search the remaining blocks that overlap our window and append their values so we can
		// merge them.
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			// Skip this block if it doesn't contain points we looking for or they have already been read
			if !cur.entry.OverlapsTimeRange(minT, maxT) || cur.read() {
				cur.markRead(minT, maxT)
				continue
			}

			var a []IntegerValue
			var v IntegerValues
			v, err := cur.r.ReadIntegerBlockAt(&cur.entry, &a)
			if err != nil {
				return nil, err
			}
			if c.col != nil {
				c.col.GetCounter(integerBlocksDecodedCounter).Add(1)
				c.col.GetCounter(integerBlocksSizeCounter).Add(int64(cur.entry.Size))
			}

			tombstones := cur.r.TombstoneRange(c.key)
			// Remove any tombstoned values
			v = excludeTombstonesIntegerValues(tombstones, v)

			// Remove values we already read
			v = v.Exclude(cur.readMin, cur.readMax)

			if v.Len() > 0 {
				// Only use values in the overlapping window
				v = v.Include(minT, maxT)
				// Merge the remaining values with the existing
				values = values.Merge(v)
			}
			cur.markRead(minT, maxT)
		}

	} else {
		// Blocks are ordered by generation, we may have values in the past in later blocks, if so,
		// expand the window to include the max time range to ensure values are returned in descending
		// order
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.MaxTime > maxT && !cur.read() {
				maxT = cur.entry.MaxTime
			}
		}

		// Find first block that overlaps our window
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.OverlapsTimeRange(minT, maxT) && !cur.read() {
				// Shrink our window so it's the intersection of the first overlapping block and the
				// first block.  We do this to minimize the region that overlaps and needs to
				// be merged.
				if cur.entry.MinTime < minT {
					minT = cur.entry.MinTime
				}
				values = values.Include(minT, maxT)
				break
			}
		}

		// Search the remaining blocks that overlap our window and append their values so we can
		// merge them.
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			// Skip this block if it doesn't contain points we looking for or they have already been read
			if !cur.entry.OverlapsTimeRange(minT, maxT) || cur.read() {
				cur.markRead(minT, maxT)
				continue
			}

			var a []IntegerValue
			var v IntegerValues
			v, err := cur.r.ReadIntegerBlockAt(&cur.entry, &a)
			if err != nil {
				return nil, err
			}
			if c.col != nil {
				c.col.GetCounter(integerBlocksDecodedCounter).Add(1)
				c.col.GetCounter(integerBlocksSizeCounter).Add(int64(cur.entry.Size))
			}
			tombstones := cur.r.TombstoneRange(c.key)
			// Remove any tombstoned values
			v = excludeTombstonesIntegerValues(tombstones, v)

			// Remove values we already read
			v = v.Exclude(cur.readMin, cur.readMax)

			// If the block we decoded should have all of it's values included, mark it as read so we
			// don't use it again.
			if v.Len() > 0 {
				v = v.Include(minT, maxT)
				// Merge the remaining values with the existing
				values = v.Merge(values)
			}
			cur.markRead(minT, maxT)
		}
	}

	first.markRead(minT, maxT)

	return values, err
}

func min(a, b int64) int64 {
	if a < b {
		return a
	}
	return b
}

func (c *KeyCursor2) ReadIntegerBlockForGroup(buf *map[string][]IntegerValue,fieldIndex int, startT int64, endT int64, expr string, duration time.Duration) (map[string][]IntegerValue , error) {
	LOOP:
	// No matching blocks to decode
	if len(c.groupCurrent) == 0 {
		return nil, nil
	}

	for _, sequenceKey := range c.sequenceKeys {
		(*buf)[sequenceKey] = (*buf)[sequenceKey][:0]
	}

	finalValues := make(map[string][]IntegerValue)
	for index, _ := range c.groupCurrent {
		// First block is the oldest block containing the points we're searching for.
		first := c.groupCurrent[index]
		var minT, maxT int64
		values := make(map[string][]IntegerValue)

		minGIT := first.groupEntry.MinTime
		maxGIT := first.groupEntry.MaxTime
		if (duration >= 3600000000000) && ((minGIT >= startT && maxGIT <= endT) || (minGIT > endT))&&
			(strings.HasPrefix(expr, "max") || strings.HasPrefix(expr, "min") || strings.HasPrefix(expr, "sum")){
			switch {
			case strings.HasPrefix(expr, "sum"):
				for key, val := range first.sequenceEntries{
					minDST := val.MinTime
					maxDST := val.MaxTime
					for i:=0; i < val.timeSlice; i++{
						t := time.Unix(0, minDST)
						nextHour := t.Truncate(time.Hour).Add(time.Hour)

						values[key] = append(values[key], IntegerValue{
							unixnano: (minDST + min(maxDST, nextHour.UnixNano())) / 2,
							value:    int64(val.sum[i][fieldIndex]),})
						minDST = nextHour.UnixNano()
					}
				}

			case strings.HasPrefix(expr, "min"):
				for key, val := range first.sequenceEntries{
					minDST := val.MinTime
					maxDST := val.MaxTime
					for i:=0; i < val.timeSlice; i++{
						t := time.Unix(0, minDST)
						nextHour := t.Truncate(time.Hour).Add(time.Hour)
						values[key] = append(values[key], IntegerValue{
							unixnano: (minDST + min(maxDST, nextHour.UnixNano())) / 2,
							value:    int64(val.min[i][fieldIndex]),})
						minDST =nextHour.UnixNano()
					}
				}
			case strings.HasPrefix(expr, "max"):
				for key, val := range first.sequenceEntries{
					minDST := val.MinTime
					maxDST := val.MaxTime
					for i:=0; i < val.timeSlice; i++{
						t := time.Unix(0, minDST)
						nextHour := t.Truncate(time.Hour).Add(time.Hour)
						values[key] = append(values[key], IntegerValue{
							unixnano: (minDST + min(maxDST, nextHour.UnixNano())) / 2,
							value:    int64(val.max[i][fieldIndex]),})
						minDST =nextHour.UnixNano()
					}
				}
			}
		}else {
			var err error
			values, err = first.r.ReadIntegerBlockAtForGroup2(&first.groupEntry, &first.sequenceEntries, buf, fieldIndex)
			if err != nil {
				return nil, err
			}
		}

		for key, value_ := range values {
			var value, tempValues IntegerValues
			value = value_
			for _, v := range value {
				if v.value != -math.MaxInt64 {
					tempValues = append(tempValues, v)
				}
			}
			value = tempValues

			if c.col != nil {
				c.col.GetCounter(integerBlocksDecodedCounter).Add(1)
				c.col.GetCounter(integerBlocksSizeCounter).Add(int64(first.groupEntry.Size))
			}

			value = value.Exclude(first.readMin, first.readMax)

			tombstones := first.r.TombstoneRange(c.key)
			value = excludeTombstonesIntegerValues(tombstones, value)

			if value.Len() == 0 && len(c.groupCurrent) > 0 {
				c.groupCurrent = c.groupCurrent[1:]
				goto LOOP
			}

			if len(c.groupCurrent) == 1 {
				if value.Len() > 0 {
					first.markRead(value.MinTime(), value.MaxTime())
				}
			}

			minT, maxT = first.readMin, first.readMax
			if value.Len() > 0 {
				minT, maxT = value.MinTime(), value.MaxTime()
			}

			for _,v :=range value {
				if finalValues[key] == nil {
					finalValues[key] = make([]IntegerValue, 0)
				}
				finalValues[key] = append(finalValues[key], v)
			}
		}
		first.markRead(minT, maxT)
	}
	return finalValues, nil
}

func (c *KeyCursor) ReadIntegerBlockForGroup(buf *[]IntegerValue,fieldIndex int, startT int64, endT int64, expr string, duration time.Duration) ([]IntegerValue, error) {
LOOP:
	// No matching blocks to decode
	if len(c.groupCurrent) == 0 {
		return nil, nil
	}

	var finalValues IntegerValues // 最终结果

	for index, _ := range c.groupCurrent {
		// First block is the oldest block containing the points we're searching for.
		first := c.groupCurrent[index]
		*buf = (*buf)[:0]
		var values IntegerValues
		var err error

		minGIT := first.groupEntry.MinTime
		maxGIT := first.groupEntry.MaxTime
		if (duration >= 3600000000000) && ((minGIT >= startT && maxGIT <= endT) || (minGIT > endT))&&
			(strings.HasPrefix(expr, "max") || strings.HasPrefix(expr, "min") || strings.HasPrefix(expr, "sum")){
			switch {
			case strings.HasPrefix(expr, "sum"):
				val := first.sequenceEntry
					minDST := val.MinTime
					maxDST := val.MaxTime
					for i:=0; i < val.timeSlice; i++{
						t := time.Unix(0, minDST)
						nextHour := t.Truncate(time.Hour).Add(time.Hour)

						values = append(values, IntegerValue{
							unixnano: (minDST + min(maxDST, nextHour.UnixNano())) / 2,
							value:    int64(val.sum[i][fieldIndex]),})
						minDST = nextHour.UnixNano()
					}
			case strings.HasPrefix(expr, "min"):
				val := first.sequenceEntry
					minDST := val.MinTime
					maxDST := val.MaxTime
					for i:=0; i < val.timeSlice; i++{
						t := time.Unix(0, minDST)
						nextHour := t.Truncate(time.Hour).Add(time.Hour)
						values = append(values, IntegerValue{
							unixnano: (minDST + min(maxDST, nextHour.UnixNano())) / 2,
							value:    int64(val.min[i][fieldIndex]),})
						minDST =nextHour.UnixNano()
					}

			case strings.HasPrefix(expr, "max"):
				val := first.sequenceEntry
					minDST := val.MinTime
					maxDST := val.MaxTime
					for i:=0; i < val.timeSlice; i++{
						t := time.Unix(0, minDST)
						nextHour := t.Truncate(time.Hour).Add(time.Hour)
						values = append(values, IntegerValue{
							unixnano: (minDST + min(maxDST, nextHour.UnixNano())) / 2,
							value:    int64(val.max[i][fieldIndex]),})
						minDST =nextHour.UnixNano()
					}
			}
		}else {
			values, err = first.r.ReadIntegerBlockAtForGroup(&first.groupEntry, &first.sequenceEntry, buf, fieldIndex)
		}

		var tempValues IntegerValues
		for _, value := range values {
			if value.value != -math.MaxInt64 {
				tempValues = append(tempValues, value)
			}
		}
		values = tempValues
		if err != nil {
			return nil, err
		}
		if c.col != nil {
			c.col.GetCounter(integerBlocksDecodedCounter).Add(1)
			c.col.GetCounter(integerBlocksSizeCounter).Add(int64(first.groupEntry.Size))
		}

		// Remove values we already read
		values = values.Exclude(first.readMin, first.readMax)

		// Remove any tombstones
		tombstones := first.r.TombstoneRange(c.key)
		values = excludeTombstonesIntegerValues(tombstones, values)
		// If there are no values in this first block (all tombstoned or previously read) and
		// we have more potential blocks too search.  Try again.
		if values.Len() == 0 && len(c.current) > 0 {
			c.current = c.current[1:]
			goto LOOP
		}

		// Only one block with this key and time range so return it
		if len(c.current) == 1 {
			if values.Len() > 0 {
				first.markRead(values.MinTime(), values.MaxTime())
			}
			return values, nil
		}

		// Use the current block time range as our overlapping window
		minT, maxT := first.readMin, first.readMax
		if values.Len() > 0 {
			minT, maxT = values.MinTime(), values.MaxTime()
		}
		if c.ascending {
			// Blocks are ordered by generation, we may have values in the past in later blocks, if so,
			// expand the window to include the min time range to ensure values are returned in ascending
			// order
			for i := 1; i < len(c.current); i++ {
				cur := c.current[i]
				if cur.entry.MinTime < minT && !cur.read() {
					minT = cur.entry.MinTime
				}
			}

			// Find first block that overlaps our window
			for i := 1; i < len(c.current); i++ {
				cur := c.current[i]
				if cur.entry.OverlapsTimeRange(minT, maxT) && !cur.read() {
					// Shrink our window so it's the intersection of the first overlapping block and the
					// first block.  We do this to minimize the region that overlaps and needs to
					// be merged.
					if cur.entry.MaxTime > maxT {
						maxT = cur.entry.MaxTime
					}
					values = values.Include(minT, maxT)
					break
				}
			}

			// Search the remaining blocks that overlap our window and append their values so we can
			// merge them.
			for i := 1; i < len(c.current); i++ {
				cur := c.current[i]
				// Skip this block if it doesn't contain points we looking for or they have already been read
				if !cur.entry.OverlapsTimeRange(minT, maxT) || cur.read() {
					cur.markRead(minT, maxT)
					continue
				}

				var a []IntegerValue
				var v IntegerValues
				v, err := cur.r.ReadIntegerBlockAt(&cur.entry, &a)
				if err != nil {
					return nil, err
				}
				if c.col != nil {
					c.col.GetCounter(integerBlocksDecodedCounter).Add(1)
					c.col.GetCounter(integerBlocksSizeCounter).Add(int64(cur.entry.Size))
				}

				tombstones := cur.r.TombstoneRange(c.key)
				// Remove any tombstoned values
				v = excludeTombstonesIntegerValues(tombstones, v)

				// Remove values we already read
				v = v.Exclude(cur.readMin, cur.readMax)

				if v.Len() > 0 {
					// Only use values in the overlapping window
					v = v.Include(minT, maxT)
					// Merge the remaining values with the existing
					values = values.Merge(v)
				}
				cur.markRead(minT, maxT)
			}

		} else {
			// Blocks are ordered by generation, we may have values in the past in later blocks, if so,
			// expand the window to include the max time range to ensure values are returned in descending
			// order
			for i := 1; i < len(c.current); i++ {
				cur := c.current[i]
				if cur.entry.MaxTime > maxT && !cur.read() {
					maxT = cur.entry.MaxTime
				}
			}

			// Find first block that overlaps our window
			for i := 1; i < len(c.current); i++ {
				cur := c.current[i]
				if cur.entry.OverlapsTimeRange(minT, maxT) && !cur.read() {
					// Shrink our window so it's the intersection of the first overlapping block and the
					// first block.  We do this to minimize the region that overlaps and needs to
					// be merged.
					if cur.entry.MinTime < minT {
						minT = cur.entry.MinTime
					}
					values = values.Include(minT, maxT)
					break
				}
			}

			// Search the remaining blocks that overlap our window and append their values so we can
			// merge them.
			for i := 1; i < len(c.current); i++ {
				cur := c.current[i]
				// Skip this block if it doesn't contain points we looking for or they have already been read
				if !cur.entry.OverlapsTimeRange(minT, maxT) || cur.read() {
					cur.markRead(minT, maxT)
					continue
				}

				var a []IntegerValue
				var v IntegerValues
				v, err := cur.r.ReadIntegerBlockAt(&cur.entry, &a)
				if err != nil {
					return nil, err
				}
				if c.col != nil {
					c.col.GetCounter(integerBlocksDecodedCounter).Add(1)
					c.col.GetCounter(integerBlocksSizeCounter).Add(int64(cur.entry.Size))
				}
				tombstones := cur.r.TombstoneRange(c.key)
				// Remove any tombstoned values
				v = excludeTombstonesIntegerValues(tombstones, v)

				// Remove values we already read
				v = v.Exclude(cur.readMin, cur.readMax)

				// If the block we decoded should have all of it's values included, mark it as read so we
				// don't use it again.
				if v.Len() > 0 {
					v = v.Include(minT, maxT)
					// Merge the remaining values with the existing
					values = v.Merge(values)
				}
				cur.markRead(minT, maxT)
			}
		}
		first.markRead(minT, maxT)

		// 往finalValues添加数据
		for _, value := range values {
			finalValues = append(finalValues, value)
		}


	}

	return finalValues, nil
}

func (c *KeyCursor2) ReadFloatBlockForGroup(buf *map[string][]FloatValue,fieldIndex int, startT int64, endT int64, expr string, duration time.Duration) (map[string][]FloatValue, error) {
LOOP:
	// No matching blocks to decode
	if len(c.groupCurrent) == 0 {
		return nil, nil
	}

	for _, sequenceKey := range c.sequenceKeys {
		(*buf)[sequenceKey] = (*buf)[sequenceKey][:0]
	}

	finalValues := make(map[string][]FloatValue)
	for index, _ := range c.groupCurrent {
		// First block is the oldest block containing the points we're searching for.
		first := c.groupCurrent[index]
		var minT, maxT int64
		values := make(map[string][]FloatValue)

		minGIT := first.groupEntry.MinTime
		maxGIT := first.groupEntry.MaxTime
		if (duration >= 3600000000000) && ((minGIT >= startT && maxGIT <= endT) || (minGIT > endT))&&
			(strings.HasPrefix(expr, "max") || strings.HasPrefix(expr, "min") || strings.HasPrefix(expr, "sum")){
			switch {
			case strings.HasPrefix(expr, "sum"):
				for key, val := range first.sequenceEntries{
					minDST := val.MinTime
					maxDST := val.MaxTime
					for i:=0; i < val.timeSlice; i++{
						t := time.Unix(0, minDST)
						nextHour := t.Truncate(time.Hour).Add(time.Hour)

						values[key] = append(values[key], FloatValue{
							unixnano: (minDST + min(maxDST, nextHour.UnixNano())) / 2,
							value:    float64(val.sum[i][fieldIndex]),})
						minDST = nextHour.UnixNano()
					}
				}

			case strings.HasPrefix(expr, "min"):
				for key, val := range first.sequenceEntries{
					minDST := val.MinTime
					maxDST := val.MaxTime
					for i:=0; i < val.timeSlice; i++{
						t := time.Unix(0, minDST)
						nextHour := t.Truncate(time.Hour).Add(time.Hour)
						values[key] = append(values[key], FloatValue{
							unixnano: (minDST + min(maxDST, nextHour.UnixNano())) / 2,
							value:    float64(val.min[i][fieldIndex]),})
						minDST =nextHour.UnixNano()
					}
				}
			case strings.HasPrefix(expr, "max"):
				for key, val := range first.sequenceEntries{
					minDST := val.MinTime
					maxDST := val.MaxTime
					for i:=0; i < val.timeSlice; i++{
						t := time.Unix(0, minDST)
						nextHour := t.Truncate(time.Hour).Add(time.Hour)
						values[key] = append(values[key], FloatValue{
							unixnano: (minDST + min(maxDST, nextHour.UnixNano())) / 2,
							value:    float64(val.max[i][fieldIndex]),})
						minDST =nextHour.UnixNano()
					}
				}
			}
		}else {
			var err error
			values, err = first.r.ReadFloatBlockAtForGroup2(&first.groupEntry, &first.sequenceEntries, buf, fieldIndex)
			if err != nil {
				return nil, err
			}
		}


		for key, value_ := range values {
			var value, tempValues FloatValues
			value = value_
			for _, v := range value {
				if v.value != -math.MaxInt64 {
					tempValues = append(tempValues, v)
				}
			}
			value = tempValues

			if c.col != nil {
				c.col.GetCounter(floatBlocksDecodedCounter).Add(1)
				c.col.GetCounter(floatBlocksSizeCounter).Add(int64(first.groupEntry.Size))
			}

			value = value.Exclude(first.readMin, first.readMax)

			tombstones := first.r.TombstoneRange(c.key)
			value = excludeTombstonesFloatValues(tombstones, value)

			if value.Len() == 0 && len(c.current) > 0 {
				c.current = c.current[1:]
				goto LOOP
			}

			if len(c.current) == 1 {
				if value.Len() > 0 {
					first.markRead(value.MinTime(), value.MaxTime())
				}
			}

			minT, maxT = first.readMin, first.readMax
			if value.Len() > 0 {
				minT, maxT = value.MinTime(), value.MaxTime()
			}

			for _,v :=range value {
				if finalValues[key] == nil {
					finalValues[key] = make([]FloatValue, 0)
				}
				finalValues[key] = append(finalValues[key], v)
			}
		}

		first.markRead(minT, maxT)
	}

	return finalValues, nil
}



func (c *KeyCursor) ReadFloatBlockForGroup(buf *[]FloatValue,fieldIndex int, startT int64, endT int64, expr string, duration time.Duration) ([]FloatValue, error) {
LOOP:
	// No matching blocks to decode
	if len(c.groupCurrent) == 0 {
		return nil, nil
	}

	var finalValues FloatValues // 最终结果

	for index, _ := range c.groupCurrent {
		// First block is the oldest block containing the points we're searching for.
		first := c.groupCurrent[index]
		*buf = (*buf)[:0]
		var values FloatValues
		var err error

		minGIT := first.groupEntry.MinTime
		maxGIT := first.groupEntry.MaxTime
		if (duration >= 3600000000000) && ((minGIT >= startT && maxGIT <= endT) || (minGIT > endT))&&
			(strings.HasPrefix(expr, "max") || strings.HasPrefix(expr, "min") || strings.HasPrefix(expr, "sum")){
			switch {
			case strings.HasPrefix(expr, "sum"):
				val := first.sequenceEntry
				minDST := val.MinTime
				maxDST := val.MaxTime
				for i:=0; i < val.timeSlice; i++{
					t := time.Unix(0, minDST)
					nextHour := t.Truncate(time.Hour).Add(time.Hour)

					values = append(values, FloatValue{
						unixnano: (minDST + min(maxDST, nextHour.UnixNano())) / 2,
						value:    float64(val.sum[i][fieldIndex]),})
					minDST = nextHour.UnixNano()
				}
			case strings.HasPrefix(expr, "min"):
				val := first.sequenceEntry
				minDST := val.MinTime
				maxDST := val.MaxTime
				for i:=0; i < val.timeSlice; i++{
					t := time.Unix(0, minDST)
					nextHour := t.Truncate(time.Hour).Add(time.Hour)
					values = append(values, FloatValue{
						unixnano: (minDST + min(maxDST, nextHour.UnixNano())) / 2,
						value:    float64(val.min[i][fieldIndex]),})
					minDST =nextHour.UnixNano()
				}

			case strings.HasPrefix(expr, "max"):
				val := first.sequenceEntry
				minDST := val.MinTime
				maxDST := val.MaxTime
				for i:=0; i < val.timeSlice; i++{
					t := time.Unix(0, minDST)
					nextHour := t.Truncate(time.Hour).Add(time.Hour)
					values = append(values, FloatValue{
						unixnano: (minDST + min(maxDST, nextHour.UnixNano())) / 2,
						value:    float64(val.max[i][fieldIndex]),})
					minDST =nextHour.UnixNano()
				}
			}
		}else {
			values, err = first.r.ReadFloatBlockAtForGroup(&first.groupEntry, &first.sequenceEntry, buf, fieldIndex)
		}
		var tempValues FloatValues
		for _, value := range values {
			if value.value != -math.MaxFloat64 {
				tempValues = append(tempValues, value)
			}
		}
		values = tempValues
		if err != nil {
			return nil, err
		}
		if c.col != nil {
			c.col.GetCounter(floatBlocksDecodedCounter).Add(1)
			c.col.GetCounter(floatBlocksSizeCounter).Add(int64(first.groupEntry.Size))
		}

		// Remove values we already read
		values = values.Exclude(first.readMin, first.readMax)

		// Remove any tombstones
		tombstones := first.r.TombstoneRange(c.key)
		values = excludeTombstonesFloatValues(tombstones, values)
		// If there are no values in this first block (all tombstoned or previously read) and
		// we have more potential blocks too search.  Try again.
		if values.Len() == 0 && len(c.current) > 0 {
			c.current = c.current[1:]
			goto LOOP
		}

		// Only one block with this key and time range so return it
		if len(c.current) == 1 {
			if values.Len() > 0 {
				first.markRead(values.MinTime(), values.MaxTime())
			}
			return values, nil
		}

		// Use the current block time range as our overlapping window
		minT, maxT := first.readMin, first.readMax
		if values.Len() > 0 {
			minT, maxT = values.MinTime(), values.MaxTime()
		}
		if c.ascending {
			// Blocks are ordered by generation, we may have values in the past in later blocks, if so,
			// expand the window to include the min time range to ensure values are returned in ascending
			// order
			for i := 1; i < len(c.current); i++ {
				cur := c.current[i]
				if cur.entry.MinTime < minT && !cur.read() {
					minT = cur.entry.MinTime
				}
			}

			// Find first block that overlaps our window
			for i := 1; i < len(c.current); i++ {
				cur := c.current[i]
				if cur.entry.OverlapsTimeRange(minT, maxT) && !cur.read() {
					// Shrink our window so it's the intersection of the first overlapping block and the
					// first block.  We do this to minimize the region that overlaps and needs to
					// be merged.
					if cur.entry.MaxTime > maxT {
						maxT = cur.entry.MaxTime
					}
					values = values.Include(minT, maxT)
					break
				}
			}

			// Search the remaining blocks that overlap our window and append their values so we can
			// merge them.
			for i := 1; i < len(c.current); i++ {
				cur := c.current[i]
				// Skip this block if it doesn't contain points we looking for or they have already been read
				if !cur.entry.OverlapsTimeRange(minT, maxT) || cur.read() {
					cur.markRead(minT, maxT)
					continue
				}

				var a []FloatValue
				var v FloatValues
				v, err := cur.r.ReadFloatBlockAt(&cur.entry, &a)
				if err != nil {
					return nil, err
				}
				if c.col != nil {
					c.col.GetCounter(floatBlocksDecodedCounter).Add(1)
					c.col.GetCounter(floatBlocksSizeCounter).Add(int64(cur.entry.Size))
				}

				tombstones := cur.r.TombstoneRange(c.key)
				// Remove any tombstoned values
				v = excludeTombstonesFloatValues(tombstones, v)

				// Remove values we already read
				v = v.Exclude(cur.readMin, cur.readMax)

				if v.Len() > 0 {
					// Only use values in the overlapping window
					v = v.Include(minT, maxT)
					// Merge the remaining values with the existing
					values = values.Merge(v)
				}
				cur.markRead(minT, maxT)
			}

		} else {
			// Blocks are ordered by generation, we may have values in the past in later blocks, if so,
			// expand the window to include the max time range to ensure values are returned in descending
			// order
			for i := 1; i < len(c.current); i++ {
				cur := c.current[i]
				if cur.entry.MaxTime > maxT && !cur.read() {
					maxT = cur.entry.MaxTime
				}
			}

			// Find first block that overlaps our window
			for i := 1; i < len(c.current); i++ {
				cur := c.current[i]
				if cur.entry.OverlapsTimeRange(minT, maxT) && !cur.read() {
					// Shrink our window so it's the intersection of the first overlapping block and the
					// first block.  We do this to minimize the region that overlaps and needs to
					// be merged.
					if cur.entry.MinTime < minT {
						minT = cur.entry.MinTime
					}
					values = values.Include(minT, maxT)
					break
				}
			}

			// Search the remaining blocks that overlap our window and append their values so we can
			// merge them.
			for i := 1; i < len(c.current); i++ {
				cur := c.current[i]
				// Skip this block if it doesn't contain points we looking for or they have already been read
				if !cur.entry.OverlapsTimeRange(minT, maxT) || cur.read() {
					cur.markRead(minT, maxT)
					continue
				}

				var a []FloatValue
				var v FloatValues
				v, err := cur.r.ReadFloatBlockAt(&cur.entry, &a)
				if err != nil {
					return nil, err
				}
				if c.col != nil {
					c.col.GetCounter(floatBlocksDecodedCounter).Add(1)
					c.col.GetCounter(floatBlocksSizeCounter).Add(int64(cur.entry.Size))
				}
				tombstones := cur.r.TombstoneRange(c.key)
				// Remove any tombstoned values
				v = excludeTombstonesFloatValues(tombstones, v)

				// Remove values we already read
				v = v.Exclude(cur.readMin, cur.readMax)

				// If the block we decoded should have all of it's values included, mark it as read so we
				// don't use it again.
				if v.Len() > 0 {
					v = v.Include(minT, maxT)
					// Merge the remaining values with the existing
					values = v.Merge(values)
				}
				cur.markRead(minT, maxT)
			}
		}

		first.markRead(minT, maxT)

		// 往finalValues添加数据
		for _, value := range values {
			finalValues = append(finalValues, value)
		}

	}

	return finalValues, nil
}

func excludeTombstonesIntegerValues(t []TimeRange, values IntegerValues) IntegerValues {
	for i := range t {
		values = values.Exclude(t[i].Min, t[i].Max)
	}
	return values
}



// ReadUnsignedBlock reads the next block as a set of unsigned values.
func (c *KeyCursor) ReadUnsignedBlock(buf *[]UnsignedValue) ([]UnsignedValue, error) {
LOOP:
	// No matching blocks to decode
	if len(c.current) == 0 {
		return nil, nil
	}

	// First block is the oldest block containing the points we're searching for.
	first := c.current[0]
	*buf = (*buf)[:0]
	var values UnsignedValues
	values, err := first.r.ReadUnsignedBlockAt(&first.entry, buf)
	if err != nil {
		return nil, err
	}
	if c.col != nil {
		c.col.GetCounter(unsignedBlocksDecodedCounter).Add(1)
		c.col.GetCounter(unsignedBlocksSizeCounter).Add(int64(first.entry.Size))
	}

	// Remove values we already read
	values = values.Exclude(first.readMin, first.readMax)

	// Remove any tombstones
	tombstones := first.r.TombstoneRange(c.key)
	values = excludeTombstonesUnsignedValues(tombstones, values)
	// If there are no values in this first block (all tombstoned or previously read) and
	// we have more potential blocks too search.  Try again.
	if values.Len() == 0 && len(c.current) > 0 {
		c.current = c.current[1:]
		goto LOOP
	}

	// Only one block with this key and time range so return it
	if len(c.current) == 1 {
		if values.Len() > 0 {
			first.markRead(values.MinTime(), values.MaxTime())
		}
		return values, nil
	}

	// Use the current block time range as our overlapping window
	minT, maxT := first.readMin, first.readMax
	if values.Len() > 0 {
		minT, maxT = values.MinTime(), values.MaxTime()
	}
	if c.ascending {
		// Blocks are ordered by generation, we may have values in the past in later blocks, if so,
		// expand the window to include the min time range to ensure values are returned in ascending
		// order
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.MinTime < minT && !cur.read() {
				minT = cur.entry.MinTime
			}
		}

		// Find first block that overlaps our window
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.OverlapsTimeRange(minT, maxT) && !cur.read() {
				// Shrink our window so it's the intersection of the first overlapping block and the
				// first block.  We do this to minimize the region that overlaps and needs to
				// be merged.
				if cur.entry.MaxTime > maxT {
					maxT = cur.entry.MaxTime
				}
				values = values.Include(minT, maxT)
				break
			}
		}

		// Search the remaining blocks that overlap our window and append their values so we can
		// merge them.
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			// Skip this block if it doesn't contain points we looking for or they have already been read
			if !cur.entry.OverlapsTimeRange(minT, maxT) || cur.read() {
				cur.markRead(minT, maxT)
				continue
			}

			var a []UnsignedValue
			var v UnsignedValues
			v, err := cur.r.ReadUnsignedBlockAt(&cur.entry, &a)
			if err != nil {
				return nil, err
			}
			if c.col != nil {
				c.col.GetCounter(unsignedBlocksDecodedCounter).Add(1)
				c.col.GetCounter(unsignedBlocksSizeCounter).Add(int64(cur.entry.Size))
			}

			tombstones := cur.r.TombstoneRange(c.key)
			// Remove any tombstoned values
			v = excludeTombstonesUnsignedValues(tombstones, v)

			// Remove values we already read
			v = v.Exclude(cur.readMin, cur.readMax)

			if v.Len() > 0 {
				// Only use values in the overlapping window
				v = v.Include(minT, maxT)
				// Merge the remaining values with the existing
				values = values.Merge(v)
			}
			cur.markRead(minT, maxT)
		}

	} else {
		// Blocks are ordered by generation, we may have values in the past in later blocks, if so,
		// expand the window to include the max time range to ensure values are returned in descending
		// order
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.MaxTime > maxT && !cur.read() {
				maxT = cur.entry.MaxTime
			}
		}

		// Find first block that overlaps our window
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.OverlapsTimeRange(minT, maxT) && !cur.read() {
				// Shrink our window so it's the intersection of the first overlapping block and the
				// first block.  We do this to minimize the region that overlaps and needs to
				// be merged.
				if cur.entry.MinTime < minT {
					minT = cur.entry.MinTime
				}
				values = values.Include(minT, maxT)
				break
			}
		}

		// Search the remaining blocks that overlap our window and append their values so we can
		// merge them.
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			// Skip this block if it doesn't contain points we looking for or they have already been read
			if !cur.entry.OverlapsTimeRange(minT, maxT) || cur.read() {
				cur.markRead(minT, maxT)
				continue
			}

			var a []UnsignedValue
			var v UnsignedValues
			v, err := cur.r.ReadUnsignedBlockAt(&cur.entry, &a)
			if err != nil {
				return nil, err
			}
			if c.col != nil {
				c.col.GetCounter(unsignedBlocksDecodedCounter).Add(1)
				c.col.GetCounter(unsignedBlocksSizeCounter).Add(int64(cur.entry.Size))
			}
			tombstones := cur.r.TombstoneRange(c.key)
			// Remove any tombstoned values
			v = excludeTombstonesUnsignedValues(tombstones, v)

			// Remove values we already read
			v = v.Exclude(cur.readMin, cur.readMax)

			// If the block we decoded should have all of it's values included, mark it as read so we
			// don't use it again.
			if v.Len() > 0 {
				v = v.Include(minT, maxT)
				// Merge the remaining values with the existing
				values = v.Merge(values)
			}
			cur.markRead(minT, maxT)
		}
	}

	first.markRead(minT, maxT)

	return values, err
}

func excludeTombstonesUnsignedValues(t []TimeRange, values UnsignedValues) UnsignedValues {
	for i := range t {
		values = values.Exclude(t[i].Min, t[i].Max)
	}
	return values
}

// ReadStringBlock reads the next block as a set of string values.
func (c *KeyCursor) ReadStringBlock(buf *[]StringValue) ([]StringValue, error) {
LOOP:
	// No matching blocks to decode
	if len(c.current) == 0 {
		return nil, nil
	}

	// First block is the oldest block containing the points we're searching for.
	first := c.current[0]
	*buf = (*buf)[:0]
	var values StringValues
	values, err := first.r.ReadStringBlockAt(&first.entry, buf)
	if err != nil {
		return nil, err
	}
	if c.col != nil {
		c.col.GetCounter(stringBlocksDecodedCounter).Add(1)
		c.col.GetCounter(stringBlocksSizeCounter).Add(int64(first.entry.Size))
	}

	// Remove values we already read
	values = values.Exclude(first.readMin, first.readMax)

	// Remove any tombstones
	tombstones := first.r.TombstoneRange(c.key)
	values = excludeTombstonesStringValues(tombstones, values)
	// If there are no values in this first block (all tombstoned or previously read) and
	// we have more potential blocks too search.  Try again.
	if values.Len() == 0 && len(c.current) > 0 {
		c.current = c.current[1:]
		goto LOOP
	}

	// Only one block with this key and time range so return it
	if len(c.current) == 1 {
		if values.Len() > 0 {
			first.markRead(values.MinTime(), values.MaxTime())
		}
		return values, nil
	}

	// Use the current block time range as our overlapping window
	minT, maxT := first.readMin, first.readMax
	if values.Len() > 0 {
		minT, maxT = values.MinTime(), values.MaxTime()
	}
	if c.ascending {
		// Blocks are ordered by generation, we may have values in the past in later blocks, if so,
		// expand the window to include the min time range to ensure values are returned in ascending
		// order
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.MinTime < minT && !cur.read() {
				minT = cur.entry.MinTime
			}
		}

		// Find first block that overlaps our window
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.OverlapsTimeRange(minT, maxT) && !cur.read() {
				// Shrink our window so it's the intersection of the first overlapping block and the
				// first block.  We do this to minimize the region that overlaps and needs to
				// be merged.
				if cur.entry.MaxTime > maxT {
					maxT = cur.entry.MaxTime
				}
				values = values.Include(minT, maxT)
				break
			}
		}

		// Search the remaining blocks that overlap our window and append their values so we can
		// merge them.
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			// Skip this block if it doesn't contain points we looking for or they have already been read
			if !cur.entry.OverlapsTimeRange(minT, maxT) || cur.read() {
				cur.markRead(minT, maxT)
				continue
			}

			var a []StringValue
			var v StringValues
			v, err := cur.r.ReadStringBlockAt(&cur.entry, &a)
			if err != nil {
				return nil, err
			}
			if c.col != nil {
				c.col.GetCounter(stringBlocksDecodedCounter).Add(1)
				c.col.GetCounter(stringBlocksSizeCounter).Add(int64(cur.entry.Size))
			}

			tombstones := cur.r.TombstoneRange(c.key)
			// Remove any tombstoned values
			v = excludeTombstonesStringValues(tombstones, v)

			// Remove values we already read
			v = v.Exclude(cur.readMin, cur.readMax)

			if v.Len() > 0 {
				// Only use values in the overlapping window
				v = v.Include(minT, maxT)
				// Merge the remaining values with the existing
				values = values.Merge(v)
			}
			cur.markRead(minT, maxT)
		}

	} else {
		// Blocks are ordered by generation, we may have values in the past in later blocks, if so,
		// expand the window to include the max time range to ensure values are returned in descending
		// order
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.MaxTime > maxT && !cur.read() {
				maxT = cur.entry.MaxTime
			}
		}

		// Find first block that overlaps our window
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.OverlapsTimeRange(minT, maxT) && !cur.read() {
				// Shrink our window so it's the intersection of the first overlapping block and the
				// first block.  We do this to minimize the region that overlaps and needs to
				// be merged.
				if cur.entry.MinTime < minT {
					minT = cur.entry.MinTime
				}
				values = values.Include(minT, maxT)
				break
			}
		}

		// Search the remaining blocks that overlap our window and append their values so we can
		// merge them.
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			// Skip this block if it doesn't contain points we looking for or they have already been read
			if !cur.entry.OverlapsTimeRange(minT, maxT) || cur.read() {
				cur.markRead(minT, maxT)
				continue
			}

			var a []StringValue
			var v StringValues
			v, err := cur.r.ReadStringBlockAt(&cur.entry, &a)
			if err != nil {
				return nil, err
			}
			if c.col != nil {
				c.col.GetCounter(stringBlocksDecodedCounter).Add(1)
				c.col.GetCounter(stringBlocksSizeCounter).Add(int64(cur.entry.Size))
			}
			tombstones := cur.r.TombstoneRange(c.key)
			// Remove any tombstoned values
			v = excludeTombstonesStringValues(tombstones, v)

			// Remove values we already read
			v = v.Exclude(cur.readMin, cur.readMax)

			// If the block we decoded should have all of it's values included, mark it as read so we
			// don't use it again.
			if v.Len() > 0 {
				v = v.Include(minT, maxT)
				// Merge the remaining values with the existing
				values = v.Merge(values)
			}
			cur.markRead(minT, maxT)
		}
	}

	first.markRead(minT, maxT)

	return values, err
}

func excludeTombstonesStringValues(t []TimeRange, values StringValues) StringValues {
	for i := range t {
		values = values.Exclude(t[i].Min, t[i].Max)
	}
	return values
}

// ReadBooleanBlock reads the next block as a set of boolean values.
func (c *KeyCursor) ReadBooleanBlock(buf *[]BooleanValue) ([]BooleanValue, error) {
LOOP:
	// No matching blocks to decode
	if len(c.current) == 0 {
		return nil, nil
	}

	// First block is the oldest block containing the points we're searching for.
	first := c.current[0]
	*buf = (*buf)[:0]
	var values BooleanValues
	values, err := first.r.ReadBooleanBlockAt(&first.entry, buf)
	if err != nil {
		return nil, err
	}
	if c.col != nil {
		c.col.GetCounter(booleanBlocksDecodedCounter).Add(1)
		c.col.GetCounter(booleanBlocksSizeCounter).Add(int64(first.entry.Size))
	}

	// Remove values we already read
	values = values.Exclude(first.readMin, first.readMax)

	// Remove any tombstones
	tombstones := first.r.TombstoneRange(c.key)
	values = excludeTombstonesBooleanValues(tombstones, values)
	// If there are no values in this first block (all tombstoned or previously read) and
	// we have more potential blocks too search.  Try again.
	if values.Len() == 0 && len(c.current) > 0 {
		c.current = c.current[1:]
		goto LOOP
	}

	// Only one block with this key and time range so return it
	if len(c.current) == 1 {
		if values.Len() > 0 {
			first.markRead(values.MinTime(), values.MaxTime())
		}
		return values, nil
	}

	// Use the current block time range as our overlapping window
	minT, maxT := first.readMin, first.readMax
	if values.Len() > 0 {
		minT, maxT = values.MinTime(), values.MaxTime()
	}
	if c.ascending {
		// Blocks are ordered by generation, we may have values in the past in later blocks, if so,
		// expand the window to include the min time range to ensure values are returned in ascending
		// order
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.MinTime < minT && !cur.read() {
				minT = cur.entry.MinTime
			}
		}

		// Find first block that overlaps our window
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.OverlapsTimeRange(minT, maxT) && !cur.read() {
				// Shrink our window so it's the intersection of the first overlapping block and the
				// first block.  We do this to minimize the region that overlaps and needs to
				// be merged.
				if cur.entry.MaxTime > maxT {
					maxT = cur.entry.MaxTime
				}
				values = values.Include(minT, maxT)
				break
			}
		}

		// Search the remaining blocks that overlap our window and append their values so we can
		// merge them.
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			// Skip this block if it doesn't contain points we looking for or they have already been read
			if !cur.entry.OverlapsTimeRange(minT, maxT) || cur.read() {
				cur.markRead(minT, maxT)
				continue
			}

			var a []BooleanValue
			var v BooleanValues
			v, err := cur.r.ReadBooleanBlockAt(&cur.entry, &a)
			if err != nil {
				return nil, err
			}
			if c.col != nil {
				c.col.GetCounter(booleanBlocksDecodedCounter).Add(1)
				c.col.GetCounter(booleanBlocksSizeCounter).Add(int64(cur.entry.Size))
			}

			tombstones := cur.r.TombstoneRange(c.key)
			// Remove any tombstoned values
			v = excludeTombstonesBooleanValues(tombstones, v)

			// Remove values we already read
			v = v.Exclude(cur.readMin, cur.readMax)

			if v.Len() > 0 {
				// Only use values in the overlapping window
				v = v.Include(minT, maxT)
				// Merge the remaining values with the existing
				values = values.Merge(v)
			}
			cur.markRead(minT, maxT)
		}

	} else {
		// Blocks are ordered by generation, we may have values in the past in later blocks, if so,
		// expand the window to include the max time range to ensure values are returned in descending
		// order
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.MaxTime > maxT && !cur.read() {
				maxT = cur.entry.MaxTime
			}
		}

		// Find first block that overlaps our window
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			if cur.entry.OverlapsTimeRange(minT, maxT) && !cur.read() {
				// Shrink our window so it's the intersection of the first overlapping block and the
				// first block.  We do this to minimize the region that overlaps and needs to
				// be merged.
				if cur.entry.MinTime < minT {
					minT = cur.entry.MinTime
				}
				values = values.Include(minT, maxT)
				break
			}
		}

		// Search the remaining blocks that overlap our window and append their values so we can
		// merge them.
		for i := 1; i < len(c.current); i++ {
			cur := c.current[i]
			// Skip this block if it doesn't contain points we looking for or they have already been read
			if !cur.entry.OverlapsTimeRange(minT, maxT) || cur.read() {
				cur.markRead(minT, maxT)
				continue
			}

			var a []BooleanValue
			var v BooleanValues
			v, err := cur.r.ReadBooleanBlockAt(&cur.entry, &a)
			if err != nil {
				return nil, err
			}
			if c.col != nil {
				c.col.GetCounter(booleanBlocksDecodedCounter).Add(1)
				c.col.GetCounter(booleanBlocksSizeCounter).Add(int64(cur.entry.Size))
			}
			tombstones := cur.r.TombstoneRange(c.key)
			// Remove any tombstoned values
			v = excludeTombstonesBooleanValues(tombstones, v)

			// Remove values we already read
			v = v.Exclude(cur.readMin, cur.readMax)

			// If the block we decoded should have all of it's values included, mark it as read so we
			// don't use it again.
			if v.Len() > 0 {
				v = v.Include(minT, maxT)
				// Merge the remaining values with the existing
				values = v.Merge(values)
			}
			cur.markRead(minT, maxT)
		}
	}

	first.markRead(minT, maxT)

	return values, err
}

func excludeTombstonesBooleanValues(t []TimeRange, values BooleanValues) BooleanValues {
	for i := range t {
		values = values.Exclude(t[i].Min, t[i].Max)
	}
	return values
}
