// Generated by tmpl
// https://github.com/benbjohnson/tmpl
//
// DO NOT EDIT!
// Source: reader.gen.go.tmpl

package tsm1

import (
	"encoding/binary"
	"fmt"
	"github.com/influxdata/influxdb/tsdb"
)

// ReadFloatBlockAt returns the float values corresponding to the given index entry.
func (t *TSMReader) ReadFloatBlockAt(entry *IndexEntry, vals *[]FloatValue) ([]FloatValue, error) {
	t.mu.RLock()
	v, err := t.accessor.readFloatBlock(entry, vals)
	t.mu.RUnlock()
	return v, err
}

// ReadFloatArrayBlockAt fills vals with the float values corresponding to the given index entry.
func (t *TSMReader) ReadFloatArrayBlockAt(entry *IndexEntry, vals *tsdb.FloatArray) error {
	t.mu.RLock()
	err := t.accessor.readFloatArrayBlock(entry, vals)
	t.mu.RUnlock()
	return err
}

// ReadIntegerBlockAt returns the integer values corresponding to the given index entry.
func (t *TSMReader) ReadIntegerBlockAt(entry *IndexEntry, vals *[]IntegerValue) ([]IntegerValue, error) {
	t.mu.RLock()
	v, err := t.accessor.readIntegerBlock(entry, vals)
	t.mu.RUnlock()
	return v, err
}

func (t *TSMReader) ReadIntegerBlockAtForGroup2(groupEntry *GroupIndexEntry, sequenceEntries *map[string]SequenceIndexEntry, vals *map[string][]IntegerValue, fieldIndex int) (map[string][]IntegerValue, error) {
	t.mu.RLock()
	v, err := t.accessorForGroup.readIntegerBlock2(groupEntry, sequenceEntries, vals, fieldIndex)
	t.mu.RUnlock()
	return v, err
}

func (t *TSMReader) ReadIntegerBlockAtForGroup(groupEntry *GroupIndexEntry, sequenceEntry *SequenceIndexEntry, vals *[]IntegerValue, fieldIndex int) ([]IntegerValue, error) {
	t.mu.RLock()
	v, err := t.accessorForGroup.readIntegerBlock(groupEntry, sequenceEntry, vals, fieldIndex)
	t.mu.RUnlock()
	return v, err
}

func (t *TSMReader) ReadFloatBlockAtForGroup2(groupEntry *GroupIndexEntry, sequenceEntries *map[string]SequenceIndexEntry, vals *map[string][]FloatValue, fieldIndex int) (map[string][]FloatValue, error) {
	t.mu.RLock()
	v, err := t.accessorForGroup.readFloatBlock2(groupEntry, sequenceEntries, vals, fieldIndex)
	t.mu.RUnlock()
	return v, err
}

func (t *TSMReader) ReadFloatBlockAtForGroup(groupEntry *GroupIndexEntry, sequenceEntry *SequenceIndexEntry, vals *[]FloatValue, fieldIndex int) ([]FloatValue, error) {
	t.mu.RLock()
	v, err := t.accessorForGroup.readFloatBlock(groupEntry, sequenceEntry, vals, fieldIndex)
	t.mu.RUnlock()
	return v, err
}

// ReadIntegerArrayBlockAt fills vals with the integer values corresponding to the given index entry.
func (t *TSMReader) ReadIntegerArrayBlockAt(entry *IndexEntry, vals *tsdb.IntegerArray) error {
	t.mu.RLock()
	err := t.accessor.readIntegerArrayBlock(entry, vals)
	t.mu.RUnlock()
	return err
}

// ReadUnsignedBlockAt returns the unsigned values corresponding to the given index entry.
func (t *TSMReader) ReadUnsignedBlockAt(entry *IndexEntry, vals *[]UnsignedValue) ([]UnsignedValue, error) {
	t.mu.RLock()
	v, err := t.accessor.readUnsignedBlock(entry, vals)
	t.mu.RUnlock()
	return v, err
}

// ReadUnsignedArrayBlockAt fills vals with the unsigned values corresponding to the given index entry.
func (t *TSMReader) ReadUnsignedArrayBlockAt(entry *IndexEntry, vals *tsdb.UnsignedArray) error {
	t.mu.RLock()
	err := t.accessor.readUnsignedArrayBlock(entry, vals)
	t.mu.RUnlock()
	return err
}

// ReadStringBlockAt returns the string values corresponding to the given index entry.
func (t *TSMReader) ReadStringBlockAt(entry *IndexEntry, vals *[]StringValue) ([]StringValue, error) {
	t.mu.RLock()
	v, err := t.accessor.readStringBlock(entry, vals)
	t.mu.RUnlock()
	return v, err
}

// ReadStringArrayBlockAt fills vals with the string values corresponding to the given index entry.
func (t *TSMReader) ReadStringArrayBlockAt(entry *IndexEntry, vals *tsdb.StringArray) error {
	t.mu.RLock()
	err := t.accessor.readStringArrayBlock(entry, vals)
	t.mu.RUnlock()
	return err
}

// ReadBooleanBlockAt returns the boolean values corresponding to the given index entry.
func (t *TSMReader) ReadBooleanBlockAt(entry *IndexEntry, vals *[]BooleanValue) ([]BooleanValue, error) {
	t.mu.RLock()
	v, err := t.accessor.readBooleanBlock(entry, vals)
	t.mu.RUnlock()
	return v, err
}

// ReadBooleanArrayBlockAt fills vals with the boolean values corresponding to the given index entry.
func (t *TSMReader) ReadBooleanArrayBlockAt(entry *IndexEntry, vals *tsdb.BooleanArray) error {
	t.mu.RLock()
	err := t.accessor.readBooleanArrayBlock(entry, vals)
	t.mu.RUnlock()
	return err
}

// blockAccessor abstracts a method of accessing blocks from a
// TSM file.
type blockAccessor interface {
	init() (*indirectIndex, error)
	read(key []byte, timestamp int64) ([]Value, error)
	readAll(key []byte) ([]Value, error)
	readBlock(entry *IndexEntry, values []Value) ([]Value, error)
	readFloatBlock(entry *IndexEntry, values *[]FloatValue) ([]FloatValue, error)
	readFloatArrayBlock(entry *IndexEntry, values *tsdb.FloatArray) error
	readIntegerBlock(entry *IndexEntry, values *[]IntegerValue) ([]IntegerValue, error)
	readIntegerArrayBlock(entry *IndexEntry, values *tsdb.IntegerArray) error
	readUnsignedBlock(entry *IndexEntry, values *[]UnsignedValue) ([]UnsignedValue, error)
	readUnsignedArrayBlock(entry *IndexEntry, values *tsdb.UnsignedArray) error
	readStringBlock(entry *IndexEntry, values *[]StringValue) ([]StringValue, error)
	readStringArrayBlock(entry *IndexEntry, values *tsdb.StringArray) error
	readBooleanBlock(entry *IndexEntry, values *[]BooleanValue) ([]BooleanValue, error)
	readBooleanArrayBlock(entry *IndexEntry, values *tsdb.BooleanArray) error
	readBytes(entry *IndexEntry, buf []byte) (uint32, []byte, error)
	rename(path string) error
	path() string
	close() error
	free() error
}

type blockAccessorForGroup interface {
	init() (*groupIndirectIndex, error)
	read(key []byte, timestamp int64) ([]Value, error)
	readGroupBytes(entry *GroupIndexEntry, buf []byte) (uint32, []byte, error)
	path() string
	free() error
	readIntegerBlock(groupEntry *GroupIndexEntry, sequenceEntry *SequenceIndexEntry, values *[]IntegerValue, fieldIndex int) ([]IntegerValue, error)
	readIntegerBlock2(groupEntry *GroupIndexEntry, sequenceEntries *map[string]SequenceIndexEntry, values *map[string][]IntegerValue, fieldIndex int) (map[string][]IntegerValue, error)
	readFloatBlock(groupEntry *GroupIndexEntry, sequenceEntry *SequenceIndexEntry, values *[]FloatValue, fieldIndex int) ([]FloatValue, error)
	readFloatBlock2(groupEntry *GroupIndexEntry, sequenceEntries *map[string]SequenceIndexEntry, values *map[string][]FloatValue, fieldIndex int) (map[string][]FloatValue, error)
	close() error
}

func (m *mmapAccessor) readFloatBlock(entry *IndexEntry, values *[]FloatValue) ([]FloatValue, error) {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < entry.Offset+int64(entry.Size) {
		m.mu.RUnlock()
		return nil, ErrTSMClosed
	}

	a, err := DecodeFloatBlock(m.b[entry.Offset+4:entry.Offset+int64(entry.Size)], values)
	m.mu.RUnlock()

	if err != nil {
		return nil, err
	}

	return a, nil
}

func (m *mmapAccessor) readFloatArrayBlock(entry *IndexEntry, values *tsdb.FloatArray) error {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < entry.Offset+int64(entry.Size) {
		m.mu.RUnlock()
		return ErrTSMClosed
	}

	err := DecodeFloatArrayBlock(m.b[entry.Offset+4:entry.Offset+int64(entry.Size)], values)
	m.mu.RUnlock()

	return err
}

// 读取multivalue的第fieldIndex个字段
func (m *mmapAccessor) readIntegerBlock(entry *IndexEntry, values *[]IntegerValue) ([]IntegerValue, error) {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < entry.Offset+int64(entry.Size) {
		m.mu.RUnlock()
		return nil, ErrTSMClosed
	}

	a, err := DecodeIntegerBlock(m.b[entry.Offset+4:entry.Offset+int64(entry.Size)], values)
	m.mu.RUnlock()

	if err != nil {
		return nil, err
	}

	return a, nil
}

func (m *mmapGroupAccessor) readIntegerBlock2(groupEntry *GroupIndexEntry, sequenceEntries *map[string]SequenceIndexEntry, values *map[string][]IntegerValue, fieldIndex int) (map[string][]IntegerValue, error) {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < groupEntry.Offset+int64(groupEntry.Size) {
		m.mu.RUnlock()
		return nil, ErrTSMClosed
	}

	for key, sequenceEntry := range *sequenceEntries {

		// 定位到SequenceBlock在文件里的绝对位置
		offset := uint64(groupEntry.Offset+sequenceEntry.Offset) + 4 // 忘了这里的4是干啥的了

		// 获取需要的数据的位置  数据块前4个字节是crc校验
		tsOffset, tsLen, dataOffset, dataLen, err := GetTimestampAndData(m.b[offset:offset+uint64(sequenceEntry.Size)], fieldIndex)
		if err != nil {
			return nil, err
		}

		// 解压缩时间戳
		tsData, err := DecodeTimestampBlockForGroup(m.b[offset+tsOffset:offset+tsOffset+tsLen], &[]int64{})
		if err != nil {
			return nil, err
		}
		// 解压缩数据块
		realData := make([]IntegerValue2, len(tsData))
		dataData, err := DecodeIntegerBlockForGroup(m.b[offset+dataOffset:offset+dataOffset+dataLen], &realData)
		if err != nil {
			return nil, err
		}

		// 组装原来的value
		if len(tsData) != len(dataData) {
			return nil, nil
		}

		newValues := make([]IntegerValue, len(tsData))

		for i := 0; i < len(tsData); i++ {
			newValues[i] = IntegerValue{unixnano: tsData[i], value: dataData[i].value}
		}

		(*values)[key] = newValues
	}

	m.mu.RUnlock()
	return *values, nil
}
func (m *mmapGroupAccessor) readIntegerBlock(groupEntry *GroupIndexEntry, sequenceEntry *SequenceIndexEntry, values *[]IntegerValue, fieldIndex int) ([]IntegerValue, error) {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < groupEntry.Offset+int64(groupEntry.Size) {
		m.mu.RUnlock()
		return nil, ErrTSMClosed
	}

	// 定位到SequenceBlock在文件里的绝对位置
	offset := uint64(groupEntry.Offset+sequenceEntry.Offset) + 4 // 忘了这里的4是干啥的了

	// 获取需要的数据的位置  数据块前4个字节是crc校验
	tsOffset, tsLen, dataOffset, dataLen, err := GetTimestampAndData(m.b[offset:offset+uint64(sequenceEntry.Size)], fieldIndex)
	if err != nil {
		return nil, err
	}

	// 解压缩时间戳
	tsData, err := DecodeTimestampBlockForGroup(m.b[offset+tsOffset:offset+tsOffset+tsLen], &[]int64{})
	if err != nil {
		return nil, err
	}
	// 解压缩数据块
	realData := make([]IntegerValue2, len(tsData))
	dataData, err := DecodeIntegerBlockForGroup(m.b[offset+dataOffset:offset+dataOffset+dataLen], &realData)
	if err != nil {
		return nil, err
	}

	// 组装原来的value
	if len(tsData) != len(dataData) {
		return nil, nil
	}

	*values = make([]IntegerValue, len(tsData))

	for i := 0; i < len(tsData); i++ {
		(*values)[i] = IntegerValue{unixnano: tsData[i], value: dataData[i].value}
	}

	m.mu.RUnlock()
	return *values, nil
}
func (m *mmapGroupAccessor) readFloatBlock2(groupEntry *GroupIndexEntry, sequenceEntries *map[string]SequenceIndexEntry, values *map[string][]FloatValue, fieldIndex int) (map[string][]FloatValue, error) {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < groupEntry.Offset+int64(groupEntry.Size) {
		m.mu.RUnlock()
		return nil, ErrTSMClosed
	}

	for key, sequenceEntry := range *sequenceEntries {
		// 定位到SequenceBlock在文件里的绝对位置
		offset := uint64(groupEntry.Offset+sequenceEntry.Offset) + 4

		// 获取需要的数据的位置  数据块前4个字节是crc校验
		tsOffset, tsLen, dataOffset, dataLen, err := GetTimestampAndData(m.b[offset:offset+uint64(sequenceEntry.Size)], fieldIndex)
		if err != nil {
			return nil, err
		}

		// 解压缩时间戳
		tsData, err := DecodeTimestampBlockForGroup(m.b[offset+tsOffset:offset+tsOffset+tsLen], &[]int64{})
		if err != nil {
			return nil, err
		}
		// 解压缩数据块
		realData := make([]FloatValue2, len(tsData))
		dataData, err := DecodeFloatBlockForGroup(m.b[offset+dataOffset:offset+dataOffset+dataLen], &realData)
		if err != nil {
			return nil, err
		}

		// 组装原来的value
		if len(tsData) != len(dataData) {
			return nil, nil
		}

		newValues := make([]FloatValue, len(tsData))

		for i := 0; i < len(tsData); i++ {
			newValues[i] = FloatValue{unixnano: tsData[i], value: dataData[i].value}
		}

		(*values)[key] = newValues
	}

	m.mu.RUnlock()
	return *values, nil
}

func (m *mmapGroupAccessor) readFloatBlock(groupEntry *GroupIndexEntry, sequenceEntry *SequenceIndexEntry, values *[]FloatValue, fieldIndex int) ([]FloatValue, error) {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < groupEntry.Offset+int64(groupEntry.Size) {
		m.mu.RUnlock()
		return nil, ErrTSMClosed
	}

	// 定位到SequenceBlock在文件里的绝对位置
	offset := uint64(groupEntry.Offset+sequenceEntry.Offset) + 4

	// 获取需要的数据的位置  数据块前4个字节是crc校验
	tsOffset, tsLen, dataOffset, dataLen, err := GetTimestampAndData(m.b[offset:offset+uint64(sequenceEntry.Size)], fieldIndex)
	if err != nil {
		return nil, err
	}

	// 解压缩时间戳
	tsData, err := DecodeTimestampBlockForGroup(m.b[offset+tsOffset:offset+tsOffset+tsLen], &[]int64{})
	if err != nil {
		return nil, err
	}
	// 解压缩数据块
	realData := make([]FloatValue2, len(tsData))
	dataData, err := DecodeFloatBlockForGroup(m.b[offset+dataOffset:offset+dataOffset+dataLen], &realData)
	if err != nil {
		return nil, err
	}

	// 组装原来的value
	if len(tsData) != len(dataData) {
		return nil, nil
	}

	*values = make([]FloatValue, len(tsData))

	for i := 0; i < len(tsData); i++ {
		(*values)[i] = FloatValue{unixnano: tsData[i], value: dataData[i].value}
	}

	m.mu.RUnlock()
	return *values, nil
}

// 根据全部文件的数据和Field的索引获取数据点长度和时间戳、数据的位置
func GetTimestampAndData(b []byte, index int) (tsOffset, tsLen, dataOffset, dataLen uint64, err error) {
	// 此时开头是数据块的开头
	// 读取时间戳数据块长度

	// 获取时间戳和数据的偏移量
	width := binary.BigEndian.Uint32(b[:4])
	selectDataOffset := binary.BigEndian.Uint32(b[4+4*index : 4+4*index+4]) // 数据的偏移

	header := uint64(4 + width*4) // 每个sequence block前面的字节数

	tsLen, i := binary.Uvarint(b[header:]) // 读取时间戳块的长度
	if i <= 0 {
		err = fmt.Errorf("unpackBlock: unable to read timestamp block length")
		return
	}
	tsOffset = header + uint64(i) // 时间戳数据块的起始位置和长度都有了

	if int(1+selectDataOffset) > len(b) {
		err = fmt.Errorf("unpackBlock: not enough data for timestamp")
		return
	}

	dataLen, i = binary.Uvarint(b[1+selectDataOffset:]) // 1是数据类型
	if i > len(b[selectDataOffset:]) {
		err = fmt.Errorf("unpackBlock: not enough data for timestamp")
		return
	}
	dataOffset = uint64(selectDataOffset) + 1 + uint64(i)
	return
}

//func GetTimestampAndData(b []byte, index int) (tsOffset, tsLen, dataOffset, dataLen uint64, err error) {
//	// 此时开头是数据块的开头
//	// 读取时间戳数据块长度
//	offset := 0
//
//	tsLen, i := binary.Uvarint(b)
//	if i <= 0 {
//		err = fmt.Errorf("unpackBlock: unable to read timestamp block length")
//		return
//	}
//	tsIdx := i + int(tsLen) // 获取时间戳的应有长度
//	if tsIdx > len(b) {
//		err = fmt.Errorf("unpackBlock: not enough data for timestamp")
//		return
//	}
//	tsOffset = uint64(i) // 时间戳数据块的起始位置和长度都有了
//
//	offset += tsIdx
//	b = b[tsIdx:] // 定位数据
//
//	// 过滤前index-1个数据点
//	for i := 0; i < index; i++ {
//		b = b[1:] // 跳过数据类型
//		tmpLen, uSize := binary.Uvarint(b)
//		if uSize <= 0 {
//			err = fmt.Errorf("unpackBlock: unable to read timestamp block length")
//			return
//		}
//		idx := uSize + int(tmpLen) // 获取时间戳的应有长度
//		if idx > len(b) {
//			err = fmt.Errorf("unpackBlock: not enough data for timestamp")
//			return
//		}
//		offset += idx + 1
//		b = b[idx:] // 定位数据
//	}
//
//	// 到了第index个数据
//	b = b[1:] // 跳过数据类型
//	dataLen, i = binary.Uvarint(b)
//	if i <= 0 {
//		err = fmt.Errorf("unpackBlock: unable to read timestamp block length")
//		return
//	}
//	dataOffset = uint64(offset + i + 1) // 数据的起始位置
//	idx := i + int(dataLen)             // 获取数据的应有长度
//	if idx > len(b) {
//		err = fmt.Errorf("unpackBlock: not enough data for timestamp")
//		return
//	}
//	return
//}

func (m *mmapAccessor) readIntegerArrayBlock(entry *IndexEntry, values *tsdb.IntegerArray) error {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < entry.Offset+int64(entry.Size) {
		m.mu.RUnlock()
		return ErrTSMClosed
	}

	err := DecodeIntegerArrayBlock(m.b[entry.Offset+4:entry.Offset+int64(entry.Size)], values)
	m.mu.RUnlock()

	return err
}

func (m *mmapAccessor) readUnsignedBlock(entry *IndexEntry, values *[]UnsignedValue) ([]UnsignedValue, error) {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < entry.Offset+int64(entry.Size) {
		m.mu.RUnlock()
		return nil, ErrTSMClosed
	}

	a, err := DecodeUnsignedBlock(m.b[entry.Offset+4:entry.Offset+int64(entry.Size)], values)
	m.mu.RUnlock()

	if err != nil {
		return nil, err
	}

	return a, nil
}

func (m *mmapAccessor) readUnsignedArrayBlock(entry *IndexEntry, values *tsdb.UnsignedArray) error {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < entry.Offset+int64(entry.Size) {
		m.mu.RUnlock()
		return ErrTSMClosed
	}

	err := DecodeUnsignedArrayBlock(m.b[entry.Offset+4:entry.Offset+int64(entry.Size)], values)
	m.mu.RUnlock()

	return err
}

func (m *mmapAccessor) readStringBlock(entry *IndexEntry, values *[]StringValue) ([]StringValue, error) {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < entry.Offset+int64(entry.Size) {
		m.mu.RUnlock()
		return nil, ErrTSMClosed
	}

	a, err := DecodeStringBlock(m.b[entry.Offset+4:entry.Offset+int64(entry.Size)], values)
	m.mu.RUnlock()

	if err != nil {
		return nil, err
	}

	return a, nil
}

func (m *mmapAccessor) readStringArrayBlock(entry *IndexEntry, values *tsdb.StringArray) error {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < entry.Offset+int64(entry.Size) {
		m.mu.RUnlock()
		return ErrTSMClosed
	}

	err := DecodeStringArrayBlock(m.b[entry.Offset+4:entry.Offset+int64(entry.Size)], values)
	m.mu.RUnlock()

	return err
}

func (m *mmapAccessor) readBooleanBlock(entry *IndexEntry, values *[]BooleanValue) ([]BooleanValue, error) {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < entry.Offset+int64(entry.Size) {
		m.mu.RUnlock()
		return nil, ErrTSMClosed
	}

	a, err := DecodeBooleanBlock(m.b[entry.Offset+4:entry.Offset+int64(entry.Size)], values)
	m.mu.RUnlock()

	if err != nil {
		return nil, err
	}

	return a, nil
}

func (m *mmapAccessor) readBooleanArrayBlock(entry *IndexEntry, values *tsdb.BooleanArray) error {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < entry.Offset+int64(entry.Size) {
		m.mu.RUnlock()
		return ErrTSMClosed
	}

	err := DecodeBooleanArrayBlock(m.b[entry.Offset+4:entry.Offset+int64(entry.Size)], values)
	m.mu.RUnlock()

	return err
}
